# Generated by Django 4.2.29 on 2026-03-29 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_recipie_4e3567_idx',
            old_name='notificatio_recipie_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_created_46ad24_idx',
            old_name='notificatio_created_idx',
        ),
    ]
