# Generated by Django 4.2.29 on 2026-03-29 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='location',
            new_name='locations_l_categor_7349ee_idx',
            old_name='locations_l_categor_idx',
        ),
        migrations.RenameIndex(
            model_name='location',
            new_name='locations_l_rating_b15c6a_idx',
            old_name='locations_l_rating_idx',
        ),
        migrations.RenameIndex(
            model_name='location',
            new_name='locations_l_latitud_739c67_idx',
            old_name='locations_l_latitu_idx',
        ),
    ]
