# Generated by Django 4.2.29 on 2026-03-29 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='review',
            new_name='reviews_rev_locatio_db2a82_idx',
            old_name='reviews_r_locatio_idx',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='reviews_rev_user_id_35ef9b_idx',
            old_name='reviews_r_user_id_idx',
        ),
    ]
